# Generated by Django 2.2 on 2020-11-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time_spent',
            new_name='timespent',
        ),
    ]
