# Generated by Django 2.2 on 2020-11-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
